apiVersion: apps/v1
kind: Deployment
metadata:
  name: oktnd6ghte
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oktnd6ghte
  template:
    metadata:
      labels:
        app: oktnd6ghte
    spec:
      containers:
      - image: okteto.dev/oktnd6ghte:latest
        name: oktnd6ghte
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: ParameterSSENCYPT
          value: "chacha20-ietf-poly1305"
        - name: Vless_UUID
          value: "5a35ed8f-4215-4430-be57-c984e4195f1d"
        - name: Vless_Path
          value: "/5a35ed8f-4215-4430-be57-c984e4195f1d-vless"
        - name: Vmess_UUID
          value: "5a35ed8f-4215-4430-be57-c984e4195f1d"
        - name: Vmess_Path
          value: "/5a35ed8f-4215-4430-be57-c984e4195f1d-vmess"
        - name: Trojan_UUID
          value: "5a35ed8f-4215-4430-be57-c984e4195f1d"
        - name: Trojan_Path
          value: "/5a35ed8f-4215-4430-be57-c984e4195f1d-trojan"
        - name: SS_UUID
          value: "5a35ed8f-4215-4430-be57-c984e4195f1d"
        - name: SS_Path
          value: "/5a35ed8f-4215-4430-be57-c984e4195f1d-ss"
        - name: Share_Path
          value: "/5a35ed8f-4215-4430-be57-c984e4195f1d-share"
