apiVersion: v1
kind: Service
metadata:
  name: oktnd6ghte
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "oktnd6ghte"
    port: 8080
  selector:
    app: oktnd6ghte
